version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 14
  pre_build:
    commands:
     - apt-get update
     - update-ca-certificates    
     - echo ${ref}
     - echo ${sha}
     - echo ${event_name}
     - export GIT_SHA=${sha}
     - export GIT_REF=${ref}
     - export GIT_REF_TYPE=${ref_type}
     - make src/main/cdk/.venv
     - export PATH=${PATH}:$(pwd)/node_modules/.bin
     - . src/main/cdk/.venv/bin/activate
     - apt-get install awscli
  build:
    commands:
     - make clean
     - make unittest 
     - make upload-builds
  post_build:
    commands:
     - make upload-reports

