version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 14
  pre_build:
    commands:
     - update-ca-certificates    
     - echo ${ref}
     - echo ${sha}
     - echo ${event_name}
     - export GIT_SHA=${sha}
     - export GIT_REF=${ref}
     - make src/main/cdk/.venv
     - . ./config.sh
     - src/main/cdk/.venv
  build:
    commands:
     - make clean install
