name: build and test
on: 
  push:
    tags:
      - environment/*
      - release/*
    branches:
      - "*"
jobs:
  codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: '"AWS CodeBuild run build" Action For GitHub Actions'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILDS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILDS_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Run CodeBuild 
        id: run-codebuild-postgres
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: releasable_initial_build
          env-vars-for-codebuild: ref, sha , event_name
        env:
          ref: ${{ github.ref }}
          event_name: ${{ github.event_name }}
          sha: ${{ github.sha }}
          ref_type: ${{ github.ref_type }}
      - name: Retrieve test reports from CodeBuild
        if: success() || failure()
        run: |
          export SHA1_START=${{ github.sha }} | cut -c -2
          export SHA1_END=${{ github.sha }} | cut -c 3-
          mkdir -p build
          aws s3 cp s3://org.murraytait.experiment.build.reports/reports/releasable/objects/${SHA1_START}/${SHA1_END} build/
      - name: Archive test reports
        if: success() || failure()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: unittest-reports
          path: build/test-reports/*
      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: Postgres Behave Tests
          report_paths: build/test-reports/unittest.xml